Competition Tournament/Models/Team.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Competition_Tournament.Models;

[Table("TEAM")]
public partial class Team
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string? Name { get; set; }

    public int? AwardsNr { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string? Motto { get; set; }

    [Column(TypeName = "date")]
    public DateTime? CreatedOn { get; set; }

    [InverseProperty("Team1")]
    public virtual ICollection<Game> GameTeam1s { get; set; } = new List<Game>();

    [InverseProperty("Team2")]
    public virtual ICollection<Game> GameTeam2s { get; set; } = new List<Game>();

    [InverseProperty("Team")]
    public virtual ICollection<Player> Players { get; set; } = new List<Player>();

    [ForeignKey("TeamId")]
    [InverseProperty("Teams")]
    public virtual ICollection<Competition> Competitions { get; set; } = new List<Competition>();
}

Competition Tournament/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Competition_Tournament.Data;
using Competition_Tournament.Models;

namespace Competition_Tournament.Controllers
{
    public class PlayersController : Controller
    {
        private readonly CompetitionManagementContext _context;

        public PlayersController(CompetitionManagementContext context)
        {
            _context = context;
        }

        // GET: Players
        public async Task<IActionResult> Index(int? id)
        {
            if (id == null)
            {
                var allPlayers = _context.Players.Include(p => p.Team);
                ViewBag.Teams = new SelectList(_context.Teams, "Id", "Name");
                return View(await allPlayers.ToListAsync());
            }
            else
            {
                var playersInTeam = _context.Players
                    .Where(p => p.TeamId == id)
                    .Include(p => p.Team);
                ViewBag.Teams = new SelectList(_context.Teams, "Id", "Name");
                return View(await playersInTeam.ToListAsync());
            }
        }

        // GET: Players/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Players == null)
            {
                return NotFound();
            }

            var player = await _context.Players
                .Include(p => p.Team)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        // GET: Players/Create
        public IActionResult Create()
        {
            ViewData["TeamId"] = new SelectList(_context.Teams, "Id", "Name");
            return View();
        }

        // POST: Players/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,LastName,FirstName,Age,TeamId")] Player player)
        {
            if (ModelState.IsValid)
            {
                _context.Add(player);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TeamId"] = new SelectList(_context.Teams, "Id", "Id", player.TeamId);
            return View(player);
        }

        // GET: Players/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Players == null)
            {
                return NotFound();
            }

            var player = await _context.Players.FindAsync(id);
            if (player == null)
            {
                return NotFound();
            }
            ViewData["TeamId"] = new SelectList(_context.Teams, "Id", "Name", player.TeamId);
            return View(player);
        }

        // POST: Players/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,LastName,FirstName,Age,TeamId")] Player player)
        {
            if (id != player.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(player);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlayerExists(player.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TeamId"] = new SelectList(_context.Teams, "Id", "Id", player.TeamId);
            return View(player);
        }

        // GET: Players/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Players == null)
            {
                return NotFound();
            }

            var player = await _context.Players
                .Include(p => p.Team)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        // POST: Players/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Players == null)
            {
                return Problem("Entity set 'CompetitionManagementContext.Players'  is null.");
            }
            var player = await _context.Players.FindAsync(id);
            if (player != null)
            {
                _context.Players.Remove(player);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlayerExists(int id)
        {
          return (_context.Players?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Competition Tournament/Controllers/TeamController.cs
using Competition_Tournament.Data;
using Competition_Tournament.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Competition_Tournament.Controllers
{
    public class TeamController : Controller
    {
        private readonly CompetitionManagementContext _context;

        public TeamController(CompetitionManagementContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Teams.ToList());
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Edit(int id)
        {
            var team = _context.Teams.Find(id);
            if (team == null)
            {
                return NotFound();
            }
            return View(team);
        }

        [HttpPost]
        public IActionResult Create(Team team)
        {
            var exist = _context.Teams.Where(c => c.Name == team.Name).FirstOrDefault();
         
            if(exist != null)
            {
                string first = exist.Name.ToLower();
                string second = team.Name.ToLower();
                if (first == second)
                {
                    ModelState.AddModelError("Name", "The name already exists");
                }
            }

            if (team.CreatedOn > DateTime.Today)
            {
                ModelState.AddModelError("CreatedOn", "The date cannot be in the future.");
            }


            if (ModelState.IsValid)
            {
                _context.Teams.Add(team);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(team);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams.FindAsync(id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var team = await _context.Teams.FindAsync(id);
            if (team != null)
            {
                var players = _context.Players.Where(p => p.TeamId == id);
                foreach (var player in players)
                {
                    // To delete the player:
                    // _context.Players.Remove(player);

                    // To disassociate the player from the team:
                    player.TeamId = null;
                }

                _context.Teams.Remove(team);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Edit(Team team)
        {
            var exist = _context.Teams.AsNoTracking().Where(c => c.Name == team.Name).FirstOrDefault();

            if (exist != null && exist.Id != team.Id)
            {
                string first = exist.Name.ToLower();
                string second = team.Name.ToLower();
                if (first == second)
                {
                    ModelState.AddModelError("Name", "The name already exists");
                }
            }

            if (team.CreatedOn > DateTime.Today)
            {
                ModelState.AddModelError("CreatedOn", "The date cannot be in the future.");
            }

            if (ModelState.IsValid)
            {
                _context.Entry(team).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(team);
        }
    }
}

Competition Tournament/Views/Team/Create.cshtml
@model Competition_Tournament.Models.Team

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Team</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" required />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AwardsNr" class="control-label">Awards Nr</label>
                <input asp-for="AwardsNr" min="0" class="form-control" required />
                <span asp-validation-for="AwardsNr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Motto" class="control-label"></label>
                <input asp-for="Motto" class="form-control" required />
                <span asp-validation-for="Motto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedOn" class="control-label">Created On</label>
                <input asp-for="CreatedOn" class="form-control" type="date" max="@DateTime.Today.ToString("yyyy-MM-dd")" required/>
                <span asp-validation-for="CreatedOn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="submit-btn" />
            </div>
        </form>
    </div>
</div>

<div>
    <a style="color: rgba(0, 206, 209, 1)" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Competition Tournament/Views/Team/Delete.cshtml
@model Competition_Tournament.Models.Team

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Team</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            Awards Nr
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AwardsNr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Motto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Motto)
        </dd>
        <dt class = "col-sm-2">
            Created On
        </dt>
        <dd class = "col-sm-10">
            @Html.Raw(Model.CreatedOn?.ToString("d"))
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a style="color: rgba(0, 206, 209, 1)" asp-action="Index">Back to List</a>
    </form>
</div>

Competition Tournament/Views/Team/Edit.cshtml
@model Competition_Tournament.Models.Team

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Team</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AwardsNr" class="control-label">Awards Nr</label>
                <input asp-for="AwardsNr" min="0" class="form-control" />
                <span asp-validation-for="AwardsNr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Motto" class="control-label"></label>
                <input asp-for="Motto" class="form-control" />
                <span asp-validation-for="Motto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedOn" class="control-label">Created On</label>
                <input asp-for="CreatedOn" class="form-control" type="date" max="@DateTime.Today.ToString("yyyy-MM-dd")" />
                <span asp-validation-for="CreatedOn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="submit-btn" />
            </div>
        </form>
    </div>
</div>

<div>
    <a style="color: rgba(0, 206, 209, 1)" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Competition Tournament/Views/Team/Index.cshtml
@model IEnumerable<Competition_Tournament.Models.Team>

@{
    ViewData["Title"] = "Index";
}

<h1 style="margin-bottom: 15px">Teams</h1>

<p>
    <a class="create-new-btn" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Awards Nr
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Motto)
            </th>
            <th>
                Created On
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AwardsNr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Motto)
            </td>
            <td>
                @Html.Raw(item.CreatedOn?.ToString("d"))
            </td>
            <td class="team-wide">
                <a class="modify" asp-action="Edit" asp-route-id="@item.Id">Edit</a> 
                <a class="modify" asp-controller="Players" asp-action="Index" asp-route-id="@item.Id">Details</a> 
                <a class="modify" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        <tr class="team-small" style="background-color: rgba(0, 98, 99, 0.7)">
            <td colspan="6">
                <div style="width: 100%; display: flex; justify-content:space-around">
                    <a class="modify" asp-action="Edit" asp-route-id="@item.Id">Edit</a> 
                    <a class="modify" asp-controller="Players" asp-action="Index" asp-route-id="@item.Id">Details</a> 
                    <a class="modify" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </div>
            </td>
        </tr>   
}
    </tbody>
</table>